package com.restaurantcraft.blockentity;
import com.restaurantcraft.config.RestaurantCraftConfig; import com.restaurantcraft.data.*; import com.restaurantcraft.entity.CustomerEntity; import com.restaurantcraft.menu.RestaurantManagementMenu; import com.restaurantcraft.registry.*; import com.restaurantcraft.util.*; import net.minecraft.core.*; import net.minecraft.nbt.*; import net.minecraft.network.chat.Component; import net.minecraft.server.level.*; import net.minecraft.world.*; import net.minecraft.world.entity.player.*; import net.minecraft.world.inventory.AbstractContainerMenu; import net.minecraft.world.item.*; import net.minecraft.world.level.*; import net.minecraft.world.level.block.entity.*; import net.minecraft.world.level.block.state.BlockState; import net.minecraft.world.phys.AABB; import net.minecraftforge.common.capabilities.*; import net.minecraftforge.common.util.LazyOptional; import net.minecraftforge.items.*; import net.minecraftforge.items.wrapper.CombinedInvWrapper; import net.minecraftforge.network.NetworkHooks; import org.jetbrains.annotations.Nullable; import java.util.*;
public class RestaurantManagementBlockEntity extends BlockEntity implements MenuProvider { public final RestaurantData data=new RestaurantData(); public final ItemStackHandler menuInventory=new ItemStackHandler(9){protected void onContentsChanged(int s){setChanged();}}; public final ItemStackHandler fridgeInventory=new ItemStackHandler(27){protected void onContentsChanged(int s){setChanged();}}; public final ItemStackHandler temporaryBusinessInventory=new ItemStackHandler(27){protected void onContentsChanged(int s){setChanged();}}; private final LazyOptional<IItemHandler> cap=LazyOptional.of(()->new CombinedInvWrapper(menuInventory,fridgeInventory)); private BusinessResult lastResult=new BusinessResult(0,0,0,0,0,0,0);
 public RestaurantManagementBlockEntity(BlockPos p, BlockState s){super(ModBlockEntities.RESTAURANT_MANAGEMENT.get(),p,s);} public Component getDisplayName(){return Component.translatable("screen.restaurant_craft.management");} @Nullable public AbstractContainerMenu createMenu(int id, Inventory inv, Player player){return new RestaurantManagementMenu(id,inv,this);} public void openMenu(ServerPlayer sp){NetworkHooks.openScreen(sp,this,worldPosition);} public void bindOwner(Player p){ if(data.ownerUuid==null){data.ownerUuid=p.getUUID();data.ownerName=p.getName().getString();data.restaurantName=data.ownerName+"的餐厅";setChanged();}}
 public boolean isOwner(Player p){return data.ownerUuid!=null && data.ownerUuid.equals(p.getUUID());} public RestaurantLevel level(){return RestaurantLevel.byStars(data.level);} public boolean canAccess(Player p){return data.ownerUuid==null||isOwner(p)||p.hasPermissions(2);} public BusinessResult lastResult(){return lastResult;}
 public void detectArea(){ if(level==null)return; RestaurantAreaUtil.ScanResult r=RestaurantAreaUtil.scan(level,level(),worldPosition); data.areaMinPos=r.min(); data.areaMaxPos=r.max(); data.entrancePos=r.entrance(); data.exitPos=r.exit(); data.decorPopularityCache=r.decorPopularity(); setChanged(); }
 public boolean startBusiness(ServerPlayer p){ if(level==null||data.isOpen)return msg(p,"message.restaurant_craft.already_open"); if((level.getDayTime()%24000)>RestaurantCraftConfig.businessCloseTime.get()) return msg(p,"message.restaurant_craft.too_late"); detectArea(); RestaurantAreaUtil.ScanResult r=RestaurantAreaUtil.scan(level,level(),worldPosition); if(r.entrance()==null||r.exit()==null)return msg(p,"message.restaurant_craft.no_entrance_exit"); if(r.tables()<1||r.chairs()<1)return msg(p,"message.restaurant_craft.need_table_chair"); if(validRecipes().isEmpty())return msg(p,"message.restaurant_craft.need_recipe"); if(RestaurantInventoryUtil.isEmpty(fridgeInventory))return msg(p,"message.restaurant_craft.need_food"); refreshPopularity(r); if(data.popularity<=0)return msg(p,"message.restaurant_craft.no_popularity"); data.isOpen=true; data.businessStartDay=level.getDayTime()/24000; data.businessStartTime=level.getGameTime(); data.currentCustomerTotal=Math.max(1,data.popularity/5); data.spawnedCustomerCount=data.finishedCustomerCount=data.failedCustomerCount=data.successfulOrders=data.failedOrders=0; RestaurantInventoryUtil.copy(fridgeInventory,temporaryBusinessInventory); RestaurantInventoryUtil.clear(fridgeInventory); msg(p,"message.restaurant_craft.business_started"); setChanged(); return true; }
 private boolean msg(ServerPlayer p,String key){p.displayClientMessage(Component.translatable(key),true); return false;} public List<DishDefinition> validRecipes(){List<DishDefinition> out=new ArrayList<>(); int max=level().recipeSlots; for(int i=0;i<max;i++){Item item=menuInventory.getStackInSlot(i).getItem(); for(var e:ModItems.RECIPE_ITEMS.entrySet()) if(e.getValue().get()==item) DishRegistry.byId(e.getKey()).ifPresent(out::add);} return out;}
 private void refreshPopularity(RestaurantAreaUtil.ScanResult r){ int dish=validRecipes().stream().mapToInt(d->d.tier().popularity).sum(); data.dishPopularityCache=dish; data.decorPopularityCache=r.decorPopularity(); data.popularity=Math.max(0,Math.min(level().popularityCap,10+dish+data.decorPopularityCache)); }
 public void serverTick(){ if(level()==null||!data.isOpen)return; if(data.spawnedCustomerCount<data.currentCustomerTotal && activeCustomers()<RestaurantCraftConfig.maxActiveCustomers.get()) spawnCustomer(); if(data.currentCustomerTotal>0 && data.finishedCustomerCount+data.failedCustomerCount>=data.currentCustomerTotal) endBusiness(false); }
 private int activeCustomers(){ if(!(level instanceof ServerLevel sl)) return 0; return sl.getEntitiesOfClass(CustomerEntity.class,new AABB(worldPosition).inflate(64),c->worldPosition.equals(c.restaurantPos())).size(); }
 private void spawnCustomer(){ if(!(level instanceof ServerLevel sl)||data.entrancePos==null)return; BlockPos pos=RestaurantCustomerUtil.findSpawn(sl,data.entrancePos); CustomerEntity c=ModEntityTypes.CUSTOMER.get().create(sl); if(c!=null){c.moveTo(pos.getX()+0.5,pos.getY(),pos.getZ()+0.5,0,0); c.assignRestaurant(worldPosition); sl.addFreshEntity(c); data.spawnedCustomerCount++; setChanged();}}
 public void onCustomerSucceeded(CustomerEntity c,DishDefinition d){ data.successfulOrders++; data.finishedCustomerCount++; data.money+=d.tier().income; setChanged(); }
 public void onCustomerFailed(){ data.failedOrders++; data.failedCustomerCount++; data.popularity=Math.max(0,data.popularity-RestaurantCraftConfig.failedOrderPopularityPenalty.get()); setChanged(); }
 public void endBusiness(boolean forced){ int before=data.popularity; if(!forced && data.failedOrders==0) data.popularity=Math.min(level().popularityCap,data.popularity+RestaurantCraftConfig.perfectBusinessPopularityBonus.get()); int income=data.successfulOrders*500; lastResult=new BusinessResult(data.currentCustomerTotal,data.successfulOrders,data.failedOrders,income,data.popularity-before,data.popularity,data.money); data.isOpen=false; RestaurantInventoryUtil.clear(temporaryBusinessInventory); RestaurantCustomerUtil.removeCustomers(level,worldPosition); RestaurantAreaUtil.releaseChairs(level,worldPosition,level()); if(RestaurantCraftConfig.clearDeviceInventoryAfterBusiness.get()) RestaurantAreaUtil.clearDevices(level,worldPosition,level()); setChanged(); }
 public boolean upgrade(ServerPlayer p){RestaurantLevel cur=level(),n=cur.next(); if(cur==n)return false; if(data.popularity<n.needPopularity||data.money<n.needMoney)return msg(p,"message.restaurant_craft.upgrade_failed"); data.money-=n.needMoney; data.level=n.stars; detectArea(); p.displayClientMessage(Component.translatable("message.restaurant_craft.upgraded",n.stars),true); setChanged(); return true;}
 public void reset(){data.level=1;data.popularity=10;data.money=0;data.isOpen=false;data.currentCustomerTotal=data.spawnedCustomerCount=data.finishedCustomerCount=data.failedCustomerCount=data.successfulOrders=data.failedOrders=0;RestaurantInventoryUtil.clear(fridgeInventory);RestaurantInventoryUtil.clear(menuInventory);setChanged();}
 protected void saveAdditional(CompoundTag t){super.saveAdditional(t); if(data.ownerUuid!=null)t.putUUID("Owner",data.ownerUuid); t.putString("OwnerName",data.ownerName);t.putString("RestaurantName",data.restaurantName);t.putInt("Level",data.level);t.putInt("Popularity",data.popularity);t.putInt("Money",data.money);t.putBoolean("Open",data.isOpen);t.putInt("Total",data.currentCustomerTotal);t.putInt("Spawned",data.spawnedCustomerCount);t.putInt("Finished",data.finishedCustomerCount);t.putInt("Failed",data.failedCustomerCount);t.putInt("SuccessOrders",data.successfulOrders);t.putInt("FailedOrders",data.failedOrders);t.putLong("StartDay",data.businessStartDay);t.putLong("StartTime",data.businessStartTime); putPos(t,"Entrance",data.entrancePos);putPos(t,"Exit",data.exitPos); t.put("Menu",menuInventory.serializeNBT());t.put("Fridge",fridgeInventory.serializeNBT());t.put("Temp",temporaryBusinessInventory.serializeNBT());}
 public void load(CompoundTag t){super.load(t); if(t.hasUUID("Owner"))data.ownerUuid=t.getUUID("Owner"); data.ownerName=t.getString("OwnerName");data.restaurantName=t.getString("RestaurantName");data.level=t.getInt("Level")==0?1:t.getInt("Level");data.popularity=t.getInt("Popularity")==0?10:t.getInt("Popularity");data.money=t.getInt("Money");data.isOpen=t.getBoolean("Open")&&!RestaurantCraftConfig.forceCloseBusinessOnWorldLoad.get();data.currentCustomerTotal=t.getInt("Total");data.spawnedCustomerCount=t.getInt("Spawned");data.finishedCustomerCount=t.getInt("Finished");data.failedCustomerCount=t.getInt("Failed");data.successfulOrders=t.getInt("SuccessOrders");data.failedOrders=t.getInt("FailedOrders");data.businessStartDay=t.getLong("StartDay");data.businessStartTime=t.getLong("StartTime");data.entrancePos=getPos(t,"Entrance");data.exitPos=getPos(t,"Exit");menuInventory.deserializeNBT(t.getCompound("Menu"));fridgeInventory.deserializeNBT(t.getCompound("Fridge"));temporaryBusinessInventory.deserializeNBT(t.getCompound("Temp"));}
 private static void putPos(CompoundTag t,String k,BlockPos p){if(p!=null)t.putLong(k,p.asLong());} private static BlockPos getPos(CompoundTag t,String k){return t.contains(k)?BlockPos.of(t.getLong(k)):null;} public <T> LazyOptional<T> getCapability(Capability<T> c, Direction d){return c==ForgeCapabilities.ITEM_HANDLER?cap.cast():super.getCapability(c,d);} public void invalidateCaps(){super.invalidateCaps();cap.invalidate();}
}
