package com.restaurantcraft.registry;
import com.restaurantcraft.RestaurantCraft; import com.restaurantcraft.block.*; import com.restaurantcraft.data.DecorType; import net.minecraft.world.level.block.Block; import net.minecraft.world.level.block.state.BlockBehaviour; import net.minecraft.world.level.material.MapColor; import net.minecraftforge.registries.*; import net.minecraftforge.eventbus.api.IEventBus; import java.util.*; import java.util.function.Supplier;
public class ModBlocks { public static final DeferredRegister<Block> BLOCKS=DeferredRegister.create(ForgeRegistries.BLOCKS, RestaurantCraft.MODID);
 public static final RegistryObject<Block> RESTAURANT_MANAGEMENT_BLOCK=BLOCKS.register("restaurant_management_block",()->new RestaurantManagementBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(3)));
 public static final RegistryObject<Block> RESTAURANT_TABLE=BLOCKS.register("restaurant_table",()->new RestaurantTableBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2)));
 public static final RegistryObject<Block> RESTAURANT_CHAIR=BLOCKS.register("restaurant_chair",()->new RestaurantChairBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2)));
 public static final RegistryObject<Block> RESTAURANT_ENTRANCE=BLOCKS.register("restaurant_entrance",()->new RestaurantEntranceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(2)));
 public static final RegistryObject<Block> RESTAURANT_EXIT=BLOCKS.register("restaurant_exit",()->new RestaurantExitBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(2)));
 public static final RegistryObject<Block> STEAMER=device("steamer"); public static final RegistryObject<Block> BOILING_POT=device("boiling_pot"); public static final RegistryObject<Block> WOK=device("wok"); public static final RegistryObject<Block> DRINK_MIXER=device("drink_mixer"); public static final RegistryObject<Block> SINK=BLOCKS.register("sink",()->new SinkBlock(BlockBehaviour.Properties.of().strength(2)));
 public static final RegistryObject<Block> SMALL_POTTED_PLANT_1=decor("small_potted_plant_1",DecorType.SMALL_POTTED_PLANT); public static final RegistryObject<Block> LARGE_POTTED_PLANT_1=decor("large_potted_plant_1",DecorType.LARGE_POTTED_PLANT); public static final RegistryObject<Block> ELECTRIC_APPLIANCE_1=decor("electric_appliance_1",DecorType.ELECTRIC_APPLIANCE); public static final RegistryObject<Block> INSTRUMENT_1=decor("instrument_1",DecorType.INSTRUMENT);
 public static final Map<String,RegistryObject<Block>> FOOD_DISPLAY_BLOCKS=new LinkedHashMap<>(); static { for (var d: com.restaurantcraft.data.DishRegistry.DISHES) FOOD_DISPLAY_BLOCKS.put(d.id(), BLOCKS.register(d.id()+"_display",()->new FoodDisplayBlock(BlockBehaviour.Properties.of().strength(0.3f).noOcclusion()))); }
 private static RegistryObject<Block> device(String id){return BLOCKS.register(id,()->new CookingDeviceBlock(id,BlockBehaviour.Properties.of().strength(2.5f)));} private static RegistryObject<Block> decor(String id, DecorType t){return BLOCKS.register(id,()->new DecorBlock(t,BlockBehaviour.Properties.of().strength(1.5f)));} public static void register(IEventBus bus){BLOCKS.register(bus);} }
